### ISSUE TITLE
Stroke disappears when fill is set to svg

### ISSUE THREAD

**Issue by nieyuyao** [lezgomatt/psd-2-svg#3]
I added fill and stroke to the vector by photoshop.

![image](https://user-images.githubusercontent.com/17698194/202640303-431bab93-57d7-4a6e-884b-3a6c5c4c1815.png)

Then convert it with `psd-2-svg` to get the following svg.

```svg
<svg xmlns="http://www.w3.org/2000/svg" width="640" height="480">
	<g id="L1_shape_1_copy">
		<defs>
			<path id="M1_path"
				d="M232 152 C232 152,382 152,382 152 C382 152,382 302,382 302 C382 302,232 302,232 302 C232 302,232 152,232 152 Z"/>
			<mask id="M1_inner_stroke_mask">
				<path fill="rgb(255, 255, 255)"
					d="M232 152 C232 152,382 152,382 152 C382 152,382 302,382 302 C382 302,232 302,232 302 C232 302,232 152,232 152 Z"/>
				<use href="#M1_path" fill="rgb(255, 255, 255)"/>
			</mask>
		</defs>
		<use href="#M1_path" fill="none" stroke="rgb(0, 0, 255)" stroke-width="40" mask="url(#M1_inner_stroke_mask)"/>
		<use href="#M1_path" fill="rgb(255, 0, 0)"/>
	</g>
</svg>
```

It doesn't show the stroke.

![image](https://user-images.githubusercontent.com/17698194/202641335-0d997d08-2eca-4d3d-a9c6-c9579e9cd55a.png)

**Comment by nieyuyao** [comment]
Whether fill `<Use>` should be inserted before stroke `<Use>`?

https://github.com/lezgomatt/psd-2-svg/blob/3d40f2c0da22fa3709831c61561fd0cfbcafa567/index.js#L100-L113

**Comment by lezgomatt** [comment]
Hi @nieyuyao, thanks for the bug report. I've fixed this bug here: https://github.com/lezgomatt/psd-2-svg/commit/cb6acddf36d93bc25f6a2cecaab3d5c098f2029e.

Please let me know if you still encounter any issue. Thanks! 😄
